export const GET_SERVICES = 'GET_SERVICES'
export const SAVE_SERVICE = 'SAVE_SERVICE'

export const GET_PERSONS = 'GET_PERSONS'
export const SAVE_PERSON = 'SAVE_PERSON'

export const GET_TOKEN_START = 'GET_TOKEN_START'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL'

export const CREATE_USER = 'CREATE_USER'